apiVersion: {{ .Values.api.ingress | default "networking.k8s.io/v1" | quote }}
kind: Ingress
metadata:
  name: testing-office-ingress-bot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "ingress-nginx-office"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
  labels:
    app: testing-office-ingress-bot
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: "ingress-nginx-office"  
  rules:
    - host: devtools-qna.sprinklr.com   # Replace with your desired hostname
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: qna-server-client-sprlink-helm
                port:
                  number: 80 